import {test,expect} from '@playwright/test';
import fs from 'node:fs';
import path from 'node:path';
const file=process.env.DEMO_CREDENTIALS_PATH||path.resolve('../../.local/demo-credentials.json');
const tag=Date.now().toString(36);
const creds=JSON.parse(fs.readFileSync(file,'utf-8'));
async function login(page:any,role='hospital_admin'){await page.goto('/');await page.getByLabel('Email',{exact:true}).fill(creds[role].email);await page.getByLabel('Password',{exact:true}).fill(creds[role].password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.getByRole('heading',{name:'Overview',exact:true})).toBeVisible()}
test('login, world isolation, explorer and all domain pages',async({page})=>{await login(page);await expect(page.getByLabel('World')).toHaveValue(/.+/);await page.getByLabel('World').selectOption({label:'base_v1'});await page.getByRole('link',{name:'Energy',exact:true}).click();await expect(page.getByRole('heading',{name:'Energy',exact:true})).toBeVisible();await expect(page.getByLabel('World').locator('option:checked')).toHaveText('base_v1');await expect(page.getByRole('img',{name:/Observed time series/})).toBeVisible();await page.getByLabel('World').selectOption({label:'extended_v1'});for(const route of ['facility','water','waste','environment','assets','parking','safety','sustainability','reports','agent','imports','models','settings']){await page.goto('/'+route);await expect(page.locator('h1')).toBeVisible();await expect(page.locator('.clock')).toBeVisible();await expect(page.locator('body')).not.toContainText('Internal Server Error')}await page.goto('/overview');await expect(page.locator('.kpis')).toBeVisible();await expect(page.locator('.chart canvas')).toBeVisible();await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:(process.env.E2E_SCREENSHOT_DIR||'../../docs/screenshots')+'/overview.png',fullPage:true})});
test('waste and maintenance create persisted records',async({page})=>{await login(page);await page.goto('/assets');await page.getByRole('button',{name:'Add asset',exact:true}).click();const d=page.getByRole('dialog');await d.getByLabel('Name *',{exact:true}).fill('Browser fixture pump '+tag);await d.getByRole('combobox',{name:'Zone',exact:true}).selectOption('WARD_A');await d.getByRole('combobox',{name:'Kind *',exact:true}).selectOption('pump');await d.getByRole('button',{name:'Save record'}).click();await expect(d).not.toBeVisible();await expect(page.getByText('Browser fixture pump '+tag,{exact:true})).toBeVisible();await page.getByRole('button',{name:'Add maintenance order',exact:true}).click();const m=page.getByRole('dialog');await m.getByLabel('Name *',{exact:true}).fill('Browser fixture inspection '+tag);await m.getByRole('combobox',{name:'Zone',exact:true}).selectOption('WARD_A');await m.getByRole('combobox',{name:'Owner',exact:true}).selectOption(creds.operations_supervisor.user_id);await m.getByRole('combobox',{name:'Asset Id *',exact:true}).selectOption({label:'Browser fixture pump '+tag+' • WARD_A'});await m.getByRole('combobox',{name:'Inspection Type *',exact:true}).selectOption('inspection');await m.getByRole('button',{name:'Save record'}).click();await expect(m).not.toBeVisible();await expect(page.getByText('Browser fixture inspection '+tag,{exact:true})).toBeVisible();await page.goto('/waste');await page.getByRole('button',{name:'Add waste batch',exact:true}).click();const w=page.getByRole('dialog');await w.getByLabel('Name *',{exact:true}).fill('Browser fixture waste batch '+tag);await w.getByRole('combobox',{name:'Zone',exact:true}).selectOption('WARD_A');await w.getByRole('combobox',{name:'Category *',exact:true}).selectOption('red');await w.getByRole('combobox',{name:'Bin Id *',exact:true}).selectOption({label:'WARD_A red • WARD_A'});await w.getByLabel('Generated Kg *',{exact:true}).fill('1.5');await w.getByRole('button',{name:'Save record'}).click();await expect(w).not.toBeVisible();await expect(page.getByText('Browser fixture waste batch '+tag,{exact:true})).toBeVisible()});
test('scenario job, comparison and report downloads',async({page})=>{await login(page);await page.goto('/simulations');await page.getByLabel('Scenario name').fill('Browser outage scenario '+tag);await page.getByLabel('Horizon hours').fill('6');await page.getByRole('button',{name:'Run simulation',exact:true}).click();await expect(page.getByRole('heading',{name:'Browser outage scenario '+tag,exact:true})).toBeVisible({timeout:90000});await page.getByLabel('Scenario name').fill('Browser alternate scenario '+tag);await page.getByRole('button',{name:'Run simulation',exact:true}).click();await expect(page.getByRole('heading',{name:'Browser alternate scenario '+tag,exact:true})).toBeVisible({timeout:90000});await page.getByLabel('Browser outage scenario '+tag,{exact:true}).check();await page.getByLabel('Browser alternate scenario '+tag,{exact:true}).check();await page.getByRole('button',{name:'Compare selected'}).click();await expect(page.getByText('baseline_run_id',{exact:false})).toBeVisible();await page.goto('/reports');await page.getByRole('button',{name:'Generate report'}).click();await expect(page.locator('.jobbox').getByText('report: completed',{exact:true})).toBeVisible({timeout:90000});await expect(page.getByRole('link',{name:'Download CSV'}).first()).toBeVisible({timeout:90000});for(const format of ['CSV','PDF','printable HTML']){const link=page.getByRole('link',{name:'Download '+format,exact:true}).first();const href=await link.getAttribute('href');expect(href).toBeTruthy();const download=await page.request.get(href!);expect(download.status()).toBe(200);const bytes=await download.body();expect(bytes.length).toBeGreaterThan(20);if(format==='PDF')expect(bytes.subarray(0,5).toString()).toBe('%PDF-');if(format==='CSV')expect(bytes.toString()).toContain('metric,value,unit,valid_rows,rows,start_utc,end_utc,source_type');if(format==='printable HTML')expect(bytes.toString()).toContain('<html')}});
test('chat live run and cancellation control',async({page})=>{test.setTimeout(300000);await login(page);const me=await page.request.get('/api/v1/me');const capabilities=(await me.json()).llm;test.skip(!capabilities.enabled||!capabilities.configured,'Live provider configuration is required; run check-llm explicitly.');await page.goto('/chat');await page.getByLabel('Message',{exact:true}).fill('Read current water reserves using your tools; show assumptions.');await page.getByRole('button',{name:'Send message'}).click();await expect(page.getByText('Tool activity & evidence',{exact:true})).toBeVisible();await expect(page.getByText(/run completed/).first()).toBeVisible({timeout:180000});await expect(page.locator('.message.assistant')).toBeVisible();await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:(process.env.E2E_SCREENSHOT_DIR||'../../docs/screenshots')+'/chat.png',fullPage:true})});
test('import duplicate job and independent action closure',async({page})=>{
 await login(page,'operations_supervisor');await page.goto('/actions');await page.getByRole('button',{name:'Create action',exact:true}).click();const d=page.getByRole('dialog');const title='Browser accountable inspection '+Date.now();await d.getByLabel('Action title *',{exact:true}).fill(title);await d.getByRole('combobox',{name:'Zone *',exact:true}).selectOption('WARD_A');await d.getByRole('combobox',{name:'Owner *',exact:true}).selectOption(creds.operations_supervisor.user_id);await d.getByRole('button',{name:'Create action',exact:true}).click();await expect(d).not.toBeVisible();
 for(const state of ['acknowledged','in progress','resolved']){const card=page.locator('.action-card').filter({has:page.getByRole('heading',{name:title,exact:true})});await card.getByRole('button',{name:state,exact:true}).click();await d.getByLabel('Reason *',{exact:true}).fill('Browser recorded inspection progression');await d.getByRole('button',{name:'Record transition'}).click();await expect(d).not.toBeVisible()}
 await page.getByRole('button',{name:'Sign out',exact:true}).click();await login(page);await page.goto('/actions');
 for(const state of ['verified','closed']){const card=page.locator('.action-card').filter({has:page.getByRole('heading',{name:title,exact:true})});await card.getByRole('button',{name:state,exact:true}).click();await d.getByLabel('Reason *',{exact:true}).fill('Independent administrator reviewed inspection');await d.getByLabel('Evidence note *',{exact:true}).fill('Synthetic inspection evidence: pump state and signed work record reviewed.');await d.getByRole('button',{name:'Record transition'}).click();await expect(d).not.toBeVisible()}
 await expect(page.locator('.action-card').filter({has:page.getByRole('heading',{name:title,exact:true})}).locator('.badge')).toHaveText('closed');await page.goto('/imports');await page.getByLabel('World').selectOption({label:'base_v1'});await page.getByRole('button',{name:'Import selected starter world'}).click();await expect(page.locator('.jobbox').getByText('import: completed',{exact:true})).toBeVisible({timeout:90000});
});
