'use client';
import {useEffect,useState} from 'react';
import * as Dialog from '@radix-ui/react-dialog';
import {api,scoped,mutation,Row,World,number,time} from '../lib/api';
import RecordEditor,{readable} from './record-editor';
const immutable=new Set(['waste_batches','pickups','parking_events','environment_readings','policy_versions','tariff_versions','emission_factor_versions','documents','agent_policies']);
export default function Ledger({world,table,title,write=false,refresh=0}:{world:World;table:string;title:string;write?:boolean;refresh?:number}){
 const [rows,setRows]=useState<Row[]>([]),[offset,setOffset]=useState(0),[more,setMore]=useState(false),[busy,setBusy]=useState(true),[error,setError]=useState(''),[edit,setEdit]=useState<Row|null|undefined>(undefined),[detail,setDetail]=useState<Row|null>(null),[version,setVersion]=useState(0);
 useEffect(()=>{setBusy(true);setError('');api(scoped('/records/'+table,world.id,{limit:25,offset})).then(r=>{setRows(r.items);setMore(r.truncated)}).catch(e=>setError(e.message)).finally(()=>setBusy(false))},[world.id,world.as_of,table,offset,version,refresh]);
 return <section className="panel"><div className="panel-head"><div><h2>{title}</h2><p className="tiny muted">Persisted {readable(table).toLowerCase()} • {world.code}</p></div>{write&&<button className="primary" onClick={()=>setEdit(null)}>Add {readable(table.replace(/ies$/,'y').replace(/batches$/,'batch').replace(/s$/,'')).toLowerCase()}</button>}</div>{error&&<p className="notice error" role="alert">{error}</p>}{busy?<p className="loading">Loading records…</p>:!rows.length?<div className="empty">No records at this world’s clock. {write?'Add a record to begin.':'The independent extended world contains the additional domain fixtures.'}</div>:<div className="table-wrap"><table><thead><tr><th>Record / zone</th><th>State</th><th>Value / context</th><th>Event time</th><th>Evidence</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><span className="record-title">{r.name||readable(r.category)}</span><p className="tiny muted">{r.zone_code||'Facility'} • {r.category}</p></td><td><span className={'badge '+(r.severity==='high'||r.severity==='critical'?'warning':'')}>{r.status}</span><p className="tiny muted">{r.source_type}</p></td><td>{r.value!==null?`${number(r.value)} ${r.unit||''}`:Object.entries(r.data).filter(([k,v])=>typeof v!=='object'&&!['body','description','notes'].includes(k)).slice(0,3).map(([k,v])=><p className="tiny" key={k}>{readable(k)}: {String(v)}</p>)}</td><td className="tiny">{time(r.event_at)}</td><td><div className="table-actions"><button onClick={()=>setDetail(r)}>Details</button>{write&&!immutable.has(table)&&<><button onClick={()=>setEdit(r)}>Edit</button><button onClick={async()=>{try{await api(scoped(`/records/${table}/${r.id}`,world.id,{expected_version:r.version}),{method:'DELETE'});setVersion(v=>v+1)}catch(e:any){setError(e.message)}}}>Archive</button></>}</div></td></tr>)}</tbody></table></div>}<div className="actionsbar" style={{marginTop:15}}><button disabled={offset===0||busy} onClick={()=>setOffset(Math.max(0,offset-25))}>Previous</button><span className="run-status">Rows {offset+1}–{offset+rows.length}</span><button disabled={!more||busy} onClick={()=>setOffset(offset+25)}>Next</button></div>{edit!==undefined&&<RecordEditor world={world} table={table} row={edit||undefined} onClose={()=>setEdit(undefined)} onSaved={()=>setVersion(v=>v+1)}/>}<Dialog.Root open={!!detail} onOpenChange={o=>{if(!o)setDetail(null)}}><Dialog.Portal><Dialog.Overlay className="overlay"/><Dialog.Content className="dialog"><Dialog.Title asChild><h2>{detail?.name||'Record evidence'}</h2></Dialog.Title><Dialog.Description>Persisted record, source and engineering assumptions. Event time uses the virtual clock.</Dialog.Description><pre className="data">{JSON.stringify(detail,null,2)}</pre><footer><Dialog.Close asChild><button>Close</button></Dialog.Close></footer></Dialog.Content></Dialog.Portal></Dialog.Root></section>
}
