'use client';
import {useEffect,useState} from 'react';
import * as Dialog from '@radix-ui/react-dialog';
import {api,scoped,mutation,Row,World} from '../lib/api';
export default function Proposals({world,approve,onSaved,refresh=0}:{world:World;approve:boolean;onSaved:()=>void;refresh?:number}) {
 const [rows,setRows]=useState<Row[]>([]),[owners,setOwners]=useState<any[]>([]),[selected,setSelected]=useState<Row|null>(null),[owner,setOwner]=useState(''),[category,setCategory]=useState('maintenance'),[note,setNote]=useState(''),[error,setError]=useState(''),[due,setDue]=useState(world.as_of.slice(0,16)),[busy,setBusy]=useState(false);
 function load(){Promise.all([api(scoped('/action-proposals',world.id)),api(scoped('/owners',world.id))]).then(([r,o])=>{setRows(r.items);setOwners(o.items)}).catch(e=>setError(e.message))}
 useEffect(load,[world.id,refresh]);
 async function save(e:React.FormEvent){e.preventDefault();if(!selected)return;setBusy(true);try{await mutation(`/action-proposals/${selected.id}/approve`,world.id,{expected_version:selected.version,review_evidence:note,action:{name:selected.name,description:selected.data.description,zone_code:selected.zone_code,owner_id:owner,category,due_at:new Date(due+'Z').toISOString(),alert_id:selected.data.alert_id||null,scenario_id:selected.data.scenario_id||null}});setSelected(null);load();onSaved()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <section className="panel"><h2>Reviewable agent proposals</h2>{error&&!selected&&<p className="notice error">{error}</p>}{rows.length?rows.map(r=><article className="action-card" key={r.id}><div className="panel-head"><h3>{r.name}</h3><span className="badge">{r.status}</span></div><p>{r.data.description}</p><p className="tiny muted">{r.zone_code} • proposal {r.id}</p>{approve&&r.status==='proposed'&&<button onClick={()=>{setSelected(r);setError('');setNote('')}}>Review and assign</button>}</article>):<p className="empty">No saved proposals. Investigation runs can draft one using scoped evidence.</p>}<Dialog.Root open={!!selected} onOpenChange={o=>{if(!o)setSelected(null)}}><Dialog.Portal><Dialog.Overlay className="overlay"/><Dialog.Content className="dialog"><Dialog.Title asChild><h2>Review proposal and assign action</h2></Dialog.Title><Dialog.Description>The reviewed proposal becomes a persisted action with an authorized owner. Evidence and current version are checked on the server.</Dialog.Description>{error&&<p className="notice error" role="alert">{error}</p>}<form onSubmit={save}><div className="form-grid"><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}>{['maintenance','water','energy','waste','environment','parking','safety','sustainability'].map(v=><option key={v}>{v}</option>)}</select></label><label>Owner *<select required value={owner} onChange={e=>setOwner(e.target.value)}><option value="">Select owner</option>{owners.map(o=><option key={o.id} value={o.id}>{o.name} • {o.role}</option>)}</select></label><label>Due time (UTC) *<input required type="datetime-local" value={due} onChange={e=>setDue(e.target.value)}/></label><label className="wide">Review evidence *<textarea required minLength={5} value={note} onChange={e=>setNote(e.target.value)}/></label></div><footer><Dialog.Close asChild><button type="button">Cancel</button></Dialog.Close><button className="primary" disabled={busy}>Approve and create action</button></footer></form></Dialog.Content></Dialog.Portal></Dialog.Root></section>
}
