'use client';
import {useEffect,useState} from 'react';
import * as Dialog from '@radix-ui/react-dialog';
import {api,scoped,mutation,Row,World} from '../lib/api';

const titles:Record<string,string>={buildings:'Building',floors:'Floor',zones:'Zone',zone_capacities:'Capacity',operating_schedules:'Operating schedule',assets:'Asset',asset_dependencies:'Dependency',maintenance_orders:'Work order',tanks:'Tank',waste_bins:'Waste bin',waste_batches:'Waste batch',pickups:'Pickup and handover',environment_readings:'Environment reading',parking_areas:'Parking area',parking_events:'Parking event',safety_incidents:'Safety incident',policy_versions:'Policy version',tariff_versions:'Tariff version',emission_factor_versions:'Carbon factor version',documents:'Operating document',agent_policies:'Agent policy version'};
export function readable(value:string){return value.replaceAll('_',' ').replace(/\b\w/g,s=>s.toUpperCase())}
export default function RecordEditor({world,table,row,onClose,onSaved}:{world:World;table:string;row?:Row;onClose:()=>void;onSaved:()=>void}){
 const [schema,setSchema]=useState<any>();const [values,setValues]=useState<Record<string,any>>(row?.data||{});const [name,setName]=useState(row?.name||'');const [zone,setZone]=useState(row?.zone_code||'');const [parent,setParent]=useState(row?.parent_id||'');const [owner,setOwner]=useState(row?.owner_id||'');const [category,setCategory]=useState(row?.category||'');const [status,setStatus]=useState(row?.status||'active');const [severity,setSeverity]=useState(row?.severity||'info');const [due,setDue]=useState(row?.due_at||'');const [refs,setRefs]=useState<Record<string,any[]>>({});const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 useEffect(()=>{Promise.all([api('/contracts'),api(scoped('/zones',world.id)),api(scoped('/owners',world.id)),...['assets','waste_bins','waste_batches','buildings','zones','parking_areas'].map(t=>api(scoped('/records/'+t,world.id)))]).then(([contracts,zones,owners,...records])=>{const s=contracts.items[table]?.schema;setSchema(s);setRefs({zones:zones.items,owners:owners.items,...Object.fromEntries(['assets','waste_bins','waste_batches','buildings','zones','parking_areas'].map((t,i)=>[t,records[i].items]))});if(!row){const defaults:Record<string,any>={};for(const[k,p]of Object.entries<any>(s?.properties||{})){if(p.default!==undefined)defaults[k]=p.default;if(p.format==='date-time')defaults[k]=world.as_of;if(p.type==='array')defaults[k]=[];}setValues(defaults)}}).catch(e=>setError(e.message));},[table,world.id,row,world.as_of]);
 function fieldSchema(p:any){return p.anyOf?.find((s:any)=>s.type!=='null')||p}
 function field(k:string,p:any){const s=fieldSchema(p);const value=values[k]??'';const label=readable(k)+(schema.required?.includes(k)?' *':'');const update=(v:any)=>setValues({...values,[k]:v});let choices:any[]=[];
 if(['asset_id','from_asset_id','to_asset_id'].includes(k))choices=refs.assets||[];if(k==='bin_id')choices=refs.waste_bins||[];
 if(choices.length)return <label key={k}>{label}<select required={schema.required?.includes(k)} value={value} onChange={e=>update(e.target.value)}><option value="">Select a scoped record</option>{choices.map(r=><option value={r.id} key={r.id}>{r.name} • {r.zone_code}</option>)}</select></label>;
 if(s.enum)return <label key={k}>{label}<select value={value} onChange={e=>update(e.target.value)} required={schema.required?.includes(k)}><option value="">Select</option>{s.enum.map((v:string)=><option key={v} value={v}>{readable(v)}</option>)}</select></label>;
 if(s.type==='boolean')return <label key={k} className="summary-line"><input type="checkbox" checked={Boolean(value)} onChange={e=>update(e.target.checked)}/>{label}</label>;
 if(s.type==='array')return <label key={k} className="wide">{label}{k==='batch_ids'?<select multiple value={value||[]} onChange={e=>update(Array.from(e.target.selectedOptions).map(o=>o.value))}>{(refs.waste_batches||[]).filter(r=>r.status==='stored').map(r=><option key={r.id} value={r.id}>{r.name} • {r.value} kg</option>)}</select>:k==='owner_pool'?<select multiple value={value||[]} onChange={e=>update(Array.from(e.target.selectedOptions).map(o=>o.value))}>{(refs.owners||[]).map(r=><option key={r.id} value={r.id}>{r.name} • {r.role}</option>)}</select>:<input value={Array.isArray(value)?value.join(', '):value} placeholder="Comma-separated values" onChange={e=>update(e.target.value.split(',').map(v=>v.trim()).filter(Boolean).map(v=>s.items?.type==='integer'?Number(v):v))}/>}<span className="schema-hint">{k==='days'?'Monday 0 through Sunday 6':'Use Ctrl / Cmd to select multiple options when shown.'}</span></label>;
 if(k==='body'||k==='description'||k==='notes')return <label className="wide" key={k}>{label}<textarea value={value} required={schema.required?.includes(k)} onChange={e=>update(e.target.value)} maxLength={s.maxLength}/></label>;
 return <label key={k}>{label}<input type={s.type==='number'||s.type==='integer'?'number':s.format==='date-time'?'datetime-local':'text'} value={s.format==='date-time'?String(value).slice(0,16):value} min={s.minimum} max={s.maximum} step={s.type==='integer'?'1':'any'} required={schema.required?.includes(k)} onChange={e=>update(s.format==='date-time'?new Date(e.target.value+'Z').toISOString():s.type==='number'||s.type==='integer'?(e.target.value===''?null:Number(e.target.value)):e.target.value)}/>{s.format==='date-time'&&<span className="schema-hint">UTC event time. Facility display uses Asia/Kolkata.</span>}</label>;
 }
 async function save(e:React.FormEvent){e.preventDefault();setError('');setBusy(true);try{const data=Object.fromEntries(Object.entries(values).filter(([k,v])=>v!==''&&v!==undefined));const body={name,zone_code:zone||null,category,status,severity,owner_id:owner||null,parent_id:parent||null,due_at:due?new Date(due).toISOString():null,data,...(row?{expected_version:row.version}:{})};await mutation('/records/'+table+(row?'/'+row.id:''),world.id,body,row?'PATCH':'POST');onSaved();onClose()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 const parentTable:Record<string,string>={floors:'buildings',zone_capacities:'zones',parking_events:'parking_areas'};
 return <Dialog.Root open onOpenChange={open=>{if(!open)onClose()}}><Dialog.Portal><Dialog.Overlay className="overlay"/><Dialog.Content className="dialog"><Dialog.Title asChild><h2>{row?'Edit':'Add'} {titles[table]||readable(table)}</h2></Dialog.Title><Dialog.Description className="muted">Saved in {world.code}. Required fields are marked *. Versioned policies and evidence are append-only.</Dialog.Description>{error&&<p className="notice error" role="alert">{error}</p>}{!schema?<p className="loading">Loading write contract…</p>:<form onSubmit={save}><div className="form-grid"><label className="wide">Name *<input value={name} onChange={e=>setName(e.target.value)} required maxLength={200}/></label><label>Zone<select value={zone} onChange={e=>setZone(e.target.value)}><option value="">Facility-wide</option>{(refs.zones||[]).map(z=><option key={z.id} value={z.zone_code}>{z.name}</option>)}</select></label><label>Category<input value={category} onChange={e=>setCategory(e.target.value)} placeholder="Domain category"/></label>{parentTable[table]&&<label>Parent record *<select required value={parent} onChange={e=>setParent(e.target.value)}><option value="">Select parent</option>{(refs[parentTable[table]]||[]).map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label>}{['maintenance_orders','assets'].includes(table)&&<><label>Owner<select value={owner} onChange={e=>setOwner(e.target.value)}><option value="">Unassigned</option>{(refs.owners||[]).map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label>Due time (UTC)<input type="datetime-local" value={due.slice(0,16)} onChange={e=>setDue(e.target.value+'Z')}/></label></>}{table==='maintenance_orders'&&<label>Status<select value={status} onChange={e=>setStatus(e.target.value)}>{['open','in_progress','resolved'].map(v=><option key={v}>{v}</option>)}</select></label>}{table==='safety_incidents'&&<label>Severity<select value={severity} onChange={e=>setSeverity(e.target.value)}>{['low','medium','high','critical'].map(v=><option key={v}>{v}</option>)}</select></label>}{Object.entries<any>(schema.properties).map(([k,p])=>field(k,p))}</div><footer><Dialog.Close asChild><button type="button">Cancel</button></Dialog.Close><button className="primary" type="submit" disabled={busy}>{busy?'Saving…':'Save record'}</button></footer></form>}</Dialog.Content></Dialog.Portal></Dialog.Root>
}
